import kotlin.math.pow
fun main() {
//    println("Pooja Solanki")
//    println("Atmiya University")

//    println("Pooja Solanki")
//    println("Somnath socity-2,street no-7,Raiya road,Rajkot")

//    print("enter first number:")
//    val num1 = readln().toInt()
//    print("enter second number:")
//    val num2 = readln().toInt()
//    println("addition:${num1+num2}")
//    println("subtraction:${num1-num2}")
//    println("multiplication:${num1*num2}")
//    println("division:${num1/num2}")

//    var p = 5000
//    var r = 10
//    var n = 2
//    val si = (p*r*n)/100
//    print(si)

//    print("enter P:")
//    val p = readln().toDouble()
//    print("enter r:")
//    val r = readln().toDouble()
//    print("enter n:")
//    val n = readln().toDouble()
//    val amount = p*(1+r/100).pow(n)
//    val ci = amount - p
//    print(ci)

//    print("enter salary:")
//    val s = readln().toDouble()
//    val bonus = (s*10)/100
//    print(bonus)

//    print("enter value in km:")
//    val km = readln().toDouble()
//    val m = km/1000
//    print(m)

//    print("enter value in km:")
//    val km = readln().toDouble()
//    val m = km*1000
//    val cm = m*100
//    val feet = m*3.28084
//    val inch = feet*12
//    println(m)
//    println(cm)
//    println(feet)
//    println(inch)

//    print("enter r:")
//    val r = readln().toDouble()
//    print("enter h:")
//    val h = readln().toDouble()
//    val V = 3.14*r*r*h
//    print(V)

//    print("enter h:")
//    val h = readln().toDouble()
//    print("enter b:")
//    val b = readln().toDouble()
//    val a = (h*b)/2
//    print(a)

    val a = "hello world"
    for(i in a.length-1 downTo 0) {
        print(a[i])
    }
    println()

}